spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  profiles:
    active:
    - dev
  servlet:
    multipart:
      max-file-size: 10MB
server:
  compression:
    enabled: true
    min-response-size: 1048576
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - image/jpeg
    - image/png
