spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/karol
    username: karol
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
       jdbc:
        lob:
         non_contextual_creation: true